name: Laravel Code Linting

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer

      - name: Install PHP Dependencies
        run: composer install --no-progress --no-suggest --prefer-dist

      - name: Install Node.js Dependencies
        run: npm install

      - name: Install PHP CodeSniffer
        run: composer require --dev squizlabs/php_codesniffer

      - name: Run PHP CodeSniffer
        run: vendor/bin/phpcs --standard=PSR12 app/

      - name: Run Blade Linter
        run: npx blade-formatter resources/views/**/*.blade.php

      - name: Run ESLint
        run: npx eslint resources/js/

      - name: Run Stylelint
        run: npx stylelint "resources/css/**/*.css"
